import type { GiftCatalogItem, GiftCategory } from '@/domain/types';

export const GIFT_CATEGORIES: GiftCategory[] = ['Primeiros Passos', 'Lua de Mel', 'Casa'];

const PRICE_CHECKED_AT = '2026-06-15';
const PRICE_SOURCE_URL = 'C:/Users/CARRE/Downloads/PRD V3_ Database Mocks Expandido - Lista de Casamento.docx';
const MINIMUM_CONTRIBUTION = 50;

export const GIFT_CATALOG: GiftCatalogItem[] = [
  {
    id: 'pp_01',
    title: 'Primeira feira do mês da casa nova',
    description: 'Aquela ida ao mercado para garantir a geladeira cheia no primeiro mês.',
    category: 'Primeiros Passos',
    imageSrc: '/presentes/pp_01.jpg',
    suggestedAmount: 85,
    minimumContribution: MINIMUM_CONTRIBUTION,
    referenceTotal: 849.9,
    quotaCount: 10,
    order: 1,
    priceSourceUrl: PRICE_SOURCE_URL,
    imageSourceUrl: 'https://images.unsplash.com/photo-1542838132-92c53300491e',
    priceCheckedAt: PRICE_CHECKED_AT,
  },
  {
    id: 'pp_02',
    title: 'Ajuda para o boleto da internet',
    description: 'Fundamental para não perdermos o contato e garantirmos o streaming.',
    category: 'Primeiros Passos',
    imageSrc: '/presentes/pp_02.jpg',
    suggestedAmount: 55,
    minimumContribution: MINIMUM_CONTRIBUTION,
    referenceTotal: 219,
    quotaCount: 4,
    order: 2,
    priceSourceUrl: PRICE_SOURCE_URL,
    imageSourceUrl: 'https://images.unsplash.com/photo-1563986768609-322da13575f3',
    priceCheckedAt: PRICE_CHECKED_AT,
  },
  {
    id: 'pp_04',
    title: 'Kit Limpeza Extrema',
    description: 'Produtos de limpeza pesada para os dias de faxina.',
    category: 'Primeiros Passos',
    imageSrc: '/presentes/pp_04.jpg',
    suggestedAmount: 65,
    minimumContribution: MINIMUM_CONTRIBUTION,
    referenceTotal: 189.9,
    quotaCount: 3,
    order: 4,
    priceSourceUrl: PRICE_SOURCE_URL,
    imageSourceUrl: 'https://www.flickr.com/photos/168245564@N05/48231563162',
    priceCheckedAt: PRICE_CHECKED_AT,
  },
  {
    id: 'pp_05',
    title: 'Rodízio de Pizza na primeira sexta',
    description: 'Porque ninguém quer cozinhar na primeira sexta-feira pós-mudança.',
    category: 'Primeiros Passos',
    imageSrc: '/presentes/pp_05.jpg',
    suggestedAmount: 55,
    minimumContribution: MINIMUM_CONTRIBUTION,
    referenceTotal: 159,
    quotaCount: 3,
    order: 5,
    priceSourceUrl: PRICE_SOURCE_URL,
    imageSourceUrl: 'https://images.unsplash.com/photo-1513104890138-7c749659a591',
    priceCheckedAt: PRICE_CHECKED_AT,
  },
  {
    id: 'pp_06',
    title: 'Reserva de Emergência da Casa',
    description: 'Aquele fundo para imprevistos da vida real: cano que vaza, lâmpada que queima, urgência que aparece.',
    category: 'Primeiros Passos',
    imageSrc: '/presentes/pp_06.jpg',
    suggestedAmount: 50,
    minimumContribution: MINIMUM_CONTRIBUTION,
    referenceTotal: 1250,
    quotaCount: 25,
    order: 6,
    priceSourceUrl: PRICE_SOURCE_URL,
    imageSourceUrl: 'https://www.flickr.com/photos/61174949@N00/3673567823',
    priceCheckedAt: PRICE_CHECKED_AT,
  },
  {
    id: 'pp_07',
    title: 'Estoque de Café Especial',
    description: 'Cápsulas e grãos selecionados para o combustível diário da casa nova.',
    category: 'Primeiros Passos',
    imageSrc: '/presentes/pp_07.jpg',
    suggestedAmount: 65,
    minimumContribution: MINIMUM_CONTRIBUTION,
    referenceTotal: 199.5,
    quotaCount: 3,
    order: 7,
    priceSourceUrl: PRICE_SOURCE_URL,
    imageSourceUrl: 'https://images.unsplash.com/photo-1509042239860-f550ce710b93',
    priceCheckedAt: PRICE_CHECKED_AT,
  },
  {
    id: 'pp_08',
    title: 'Assinatura Anual de Streaming',
    description: 'Para as noites de cinema em casa no sofa novo.',
    category: 'Primeiros Passos',
    imageSrc: '/presentes/pp_08.jpg',
    suggestedAmount: 90,
    minimumContribution: MINIMUM_CONTRIBUTION,
    referenceTotal: 538.8,
    quotaCount: 6,
    order: 8,
    priceSourceUrl: PRICE_SOURCE_URL,
    imageSourceUrl: 'https://images.unsplash.com/photo-1522869635100-9f4c5e86aa37',
    priceCheckedAt: PRICE_CHECKED_AT,
  },
  {
    id: 'pp_09',
    title: 'Primeiro Churrasco na Casa Nova',
    description: 'Carnes, carvão e bebidas para inaugurar a casa com pessoas queridas.',
    category: 'Primeiros Passos',
    imageSrc: '/presentes/pp_09.jpg',
    suggestedAmount: 90,
    minimumContribution: MINIMUM_CONTRIBUTION,
    referenceTotal: 359,
    quotaCount: 4,
    order: 9,
    priceSourceUrl: PRICE_SOURCE_URL,
    imageSourceUrl: 'https://images.unsplash.com/photo-1555939594-58d7cb561ad1',
    priceCheckedAt: PRICE_CHECKED_AT,
  },
  {
    id: 'pp_10',
    title: 'Jogo de Ferramentas Básico',
    description: 'Kit de chaves e furadeira para pendurar quadros, montar móveis e resolver o necessário.',
    category: 'Primeiros Passos',
    imageSrc: '/presentes/pp_10.jpg',
    suggestedAmount: 60,
    minimumContribution: MINIMUM_CONTRIBUTION,
    referenceTotal: 229.9,
    quotaCount: 4,
    order: 10,
    priceSourceUrl: PRICE_SOURCE_URL,
    imageSourceUrl: 'https://images.unsplash.com/photo-1581147036324-c17ac41dfa6c',
    priceCheckedAt: PRICE_CHECKED_AT,
  },
  {
    id: 'lm_01',
    title: 'Café da manhã em Trancoso',
    description: 'Café da manhã com frutas, tapioca e calma antes de aproveitar o litoral sul da Bahia.',
    category: 'Lua de Mel',
    imageSrc: '/presentes/lm_01.jpg',
    suggestedAmount: 70,
    minimumContribution: MINIMUM_CONTRIBUTION,
    referenceTotal: 139,
    quotaCount: 2,
    order: 11,
    priceSourceUrl: PRICE_SOURCE_URL,
    imageSourceUrl: 'https://www.flickr.com/photos/8865243@N02/9422077843',
    priceCheckedAt: PRICE_CHECKED_AT,
  },
  {
    id: 'lm_02',
    title: 'Passeio de barco pelo litoral de Trancoso',
    description: 'Passeio pelas praias e falésias da região, com mar azul e ritmo de lua de mel.',
    category: 'Lua de Mel',
    imageSrc: '/presentes/lm_02.jpg',
    suggestedAmount: 70,
    minimumContribution: MINIMUM_CONTRIBUTION,
    referenceTotal: 429,
    quotaCount: 6,
    order: 12,
    priceSourceUrl: PRICE_SOURCE_URL,
    imageSourceUrl: 'https://www.flickr.com/photos/33345813@N00/2419929765',
    priceCheckedAt: PRICE_CHECKED_AT,
  },
  {
    id: 'lm_03',
    title: 'Jantar romântico no Quadrado',
    description: 'Uma noite especial nos restaurantes charmosos do Quadrado de Trancoso.',
    category: 'Lua de Mel',
    imageSrc: '/presentes/lm_03.jpg',
    suggestedAmount: 105,
    minimumContribution: MINIMUM_CONTRIBUTION,
    referenceTotal: 1249,
    quotaCount: 12,
    order: 13,
    priceSourceUrl: PRICE_SOURCE_URL,
    imageSourceUrl: 'https://www.flickr.com/photos/7202153@N03/51388519295',
    priceCheckedAt: PRICE_CHECKED_AT,
  },
  {
    id: 'lm_04',
    title: 'Day use em praia de Trancoso',
    description: 'Um dia de estrutura na praia, com sombra, conforto e vista para o mar.',
    category: 'Lua de Mel',
    imageSrc: '/presentes/lm_04.jpg',
    suggestedAmount: 80,
    minimumContribution: MINIMUM_CONTRIBUTION,
    referenceTotal: 319,
    quotaCount: 4,
    order: 14,
    priceSourceUrl: PRICE_SOURCE_URL,
    imageSourceUrl: 'https://www.flickr.com/photos/7387467@N04/45099716062',
    priceCheckedAt: PRICE_CHECKED_AT,
  },
  {
    id: 'lm_05',
    title: 'Passeio pelo Quadrado histórico',
    description: 'Caminhada pelo Quadrado, casinhas coloridas, igreja histórica e fim de tarde baiano.',
    category: 'Lua de Mel',
    imageSrc: '/presentes/lm_05.jpg',
    suggestedAmount: 75,
    minimumContribution: MINIMUM_CONTRIBUTION,
    referenceTotal: 219,
    quotaCount: 3,
    order: 15,
    priceSourceUrl: PRICE_SOURCE_URL,
    imageSourceUrl: 'https://www.flickr.com/photos/8865243@N02/9406318207',
    priceCheckedAt: PRICE_CHECKED_AT,
  },
  {
    id: 'lm_06',
    title: 'Jantar de despedida em Trancoso',
    description: 'Comida baiana, drinks e uma última noite tranquila antes da volta para casa.',
    category: 'Lua de Mel',
    imageSrc: '/presentes/lm_06.jpg',
    suggestedAmount: 100,
    minimumContribution: MINIMUM_CONTRIBUTION,
    referenceTotal: 489,
    quotaCount: 5,
    order: 16,
    priceSourceUrl: PRICE_SOURCE_URL,
    imageSourceUrl: 'https://www.flickr.com/photos/25509772@N00/4647169120',
    priceCheckedAt: PRICE_CHECKED_AT,
  },
  {
    id: 'lm_07',
    title: 'Visita à Praia do Espelho',
    description: 'Bate-volta para uma das praias mais bonitas da Bahia, entre falésias e águas claras.',
    category: 'Lua de Mel',
    imageSrc: '/presentes/lm_07.jpg',
    suggestedAmount: 70,
    minimumContribution: MINIMUM_CONTRIBUTION,
    referenceTotal: 349.9,
    quotaCount: 5,
    order: 17,
    priceSourceUrl: PRICE_SOURCE_URL,
    imageSourceUrl: 'https://www.flickr.com/photos/56069869@N00/3027669695',
    priceCheckedAt: PRICE_CHECKED_AT,
  },
  {
    id: 'lm_08',
    title: 'Drinks ao pôr do sol',
    description: 'Brinde de fim de tarde com vista bonita, música leve e clima de férias.',
    category: 'Lua de Mel',
    imageSrc: '/presentes/lm_08.jpg',
    suggestedAmount: 100,
    minimumContribution: MINIMUM_CONTRIBUTION,
    referenceTotal: 589,
    quotaCount: 6,
    order: 18,
    priceSourceUrl: PRICE_SOURCE_URL,
    imageSourceUrl: 'https://www.rawpixel.com/image/5943474/free-public-domain-cc0-photo',
    priceCheckedAt: PRICE_CHECKED_AT,
  },
  {
    id: 'lm_09',
    title: 'Transfer Porto Seguro-Trancoso',
    description: 'Transporte seguro entre o aeroporto de Porto Seguro e a hospedagem em Trancoso.',
    category: 'Lua de Mel',
    imageSrc: '/presentes/lm_09.jpg',
    suggestedAmount: 85,
    minimumContribution: MINIMUM_CONTRIBUTION,
    referenceTotal: 419,
    quotaCount: 5,
    order: 19,
    priceSourceUrl: PRICE_SOURCE_URL,
    imageSourceUrl: 'https://www.flickr.com/photos/95572727@N00/24129711197',
    priceCheckedAt: PRICE_CHECKED_AT,
  },
  {
    id: 'lm_10',
    title: 'Noite de música no Quadrado',
    description: 'Uma noite de música ao vivo e caminhada pelo Quadrado iluminado.',
    category: 'Lua de Mel',
    imageSrc: '/presentes/lm_10.jpg',
    suggestedAmount: 95,
    minimumContribution: MINIMUM_CONTRIBUTION,
    referenceTotal: 479,
    quotaCount: 5,
    order: 20,
    priceSourceUrl: PRICE_SOURCE_URL,
    imageSourceUrl: 'https://www.flickr.com/photos/27330325@N08/2722387472',
    priceCheckedAt: PRICE_CHECKED_AT,
  },
  {
    id: 'lm_11',
    title: 'Almoço de frutos do mar',
    description: 'Peixe fresco, moqueca ou frutos do mar para aproveitar o melhor da costa baiana.',
    category: 'Lua de Mel',
    imageSrc: '/presentes/lm_11.jpg',
    suggestedAmount: 85,
    minimumContribution: MINIMUM_CONTRIBUTION,
    referenceTotal: 259,
    quotaCount: 3,
    order: 21,
    priceSourceUrl: PRICE_SOURCE_URL,
    imageSourceUrl: 'https://www.flickr.com/photos/25056484@N00/470041018',
    priceCheckedAt: PRICE_CHECKED_AT,
  },
  {
    id: 'lm_12',
    title: 'Hospedagem especial em Trancoso',
    description: 'Parte da estadia da lua de mel perto do Quadrado e das praias de Trancoso.',
    category: 'Lua de Mel',
    imageSrc: '/presentes/lm_12.jpg',
    suggestedAmount: 150,
    minimumContribution: MINIMUM_CONTRIBUTION,
    referenceTotal: 1459,
    quotaCount: 10,
    order: 22,
    priceSourceUrl: PRICE_SOURCE_URL,
    imageSourceUrl: 'https://www.flickr.com/photos/13491639@N00/2807719023',
    priceCheckedAt: PRICE_CHECKED_AT,
  },
  {
    id: 'cs_01',
    title: 'Robô Aspirador Inteligente',
    description: 'Para a casa ficar limpa enquanto a gente trabalha.',
    category: 'Casa',
    imageSrc: '/presentes/cs_01.jpg',
    suggestedAmount: 105,
    minimumContribution: MINIMUM_CONTRIBUTION,
    referenceTotal: 1549.9,
    quotaCount: 15,
    order: 23,
    priceSourceUrl: PRICE_SOURCE_URL,
    imageSourceUrl: 'https://www.flickr.com/photos/29904699@N00/282268782',
    priceCheckedAt: PRICE_CHECKED_AT,
  },
  {
    id: 'cs_02',
    title: 'Máquina de Café Expresso',
    description: 'Combustível diário com qualidade profissional.',
    category: 'Casa',
    imageSrc: '/presentes/cs_02.jpg',
    suggestedAmount: 85,
    minimumContribution: MINIMUM_CONTRIBUTION,
    referenceTotal: 829,
    quotaCount: 10,
    order: 24,
    priceSourceUrl: PRICE_SOURCE_URL,
    imageSourceUrl: 'https://images.unsplash.com/photo-1517701604599-bb29b565090c',
    priceCheckedAt: PRICE_CHECKED_AT,
  },
  {
    id: 'cs_03',
    title: 'Jogo de Panelas Antiaderentes',
    description: 'Para não queimar o jantar.',
    category: 'Casa',
    imageSrc: '/presentes/cs_03.jpg',
    suggestedAmount: 80,
    minimumContribution: MINIMUM_CONTRIBUTION,
    referenceTotal: 649,
    quotaCount: 8,
    order: 25,
    priceSourceUrl: PRICE_SOURCE_URL,
    imageSourceUrl: 'https://www.flickr.com/photos/154900222@N05/26128230038',
    priceCheckedAt: PRICE_CHECKED_AT,
  },
  {
    id: 'cs_04',
    title: 'Air Fryer 5 Litros',
    description: 'A salvadora das refeições rápidas e saudáveis.',
    category: 'Casa',
    imageSrc: '/presentes/cs_04.jpg',
    suggestedAmount: 80,
    minimumContribution: MINIMUM_CONTRIBUTION,
    referenceTotal: 479.9,
    quotaCount: 6,
    order: 26,
    priceSourceUrl: PRICE_SOURCE_URL,
    imageSourceUrl: 'https://www.flickr.com/photos/11955713@N00/5670943580',
    priceCheckedAt: PRICE_CHECKED_AT,
  },
  {
    id: 'cs_05',
    title: 'Jogo de Lençóis 400 Fios',
    description: 'Conforto máximo para o descanso.',
    category: 'Casa',
    imageSrc: '/presentes/cs_05.jpg',
    suggestedAmount: 85,
    minimumContribution: MINIMUM_CONTRIBUTION,
    referenceTotal: 419,
    quotaCount: 5,
    order: 27,
    priceSourceUrl: PRICE_SOURCE_URL,
    imageSourceUrl: 'https://images.unsplash.com/photo-1522771739844-6a9f6d5f14af',
    priceCheckedAt: PRICE_CHECKED_AT,
  },
  {
    id: 'cs_06',
    title: 'Faqueiro Inox 32 Peças',
    description: 'Para receber visitas com a mesa arrumada no dia a dia.',
    category: 'Casa',
    imageSrc: '/presentes/cs_06.jpg',
    suggestedAmount: 90,
    minimumContribution: MINIMUM_CONTRIBUTION,
    referenceTotal: 359,
    quotaCount: 4,
    order: 28,
    priceSourceUrl: PRICE_SOURCE_URL,
    imageSourceUrl: 'https://www.rawpixel.com/image/5920805/photo-image-public-domain-white-free',
    priceCheckedAt: PRICE_CHECKED_AT,
  },
  {
    id: 'cs_07',
    title: 'Smart TV 55" 4K',
    description: 'Para assistir séries e filmes com alta qualidade.',
    category: 'Casa',
    imageSrc: '/presentes/cs_07.jpg',
    suggestedAmount: 145,
    minimumContribution: MINIMUM_CONTRIBUTION,
    referenceTotal: 2899,
    quotaCount: 20,
    order: 29,
    priceSourceUrl: PRICE_SOURCE_URL,
    imageSourceUrl: 'https://images.unsplash.com/photo-1593305841991-05c297ba4575',
    priceCheckedAt: PRICE_CHECKED_AT,
  },
  {
    id: 'cs_08',
    title: 'Micro-ondas Espelhado 32L',
    description: 'Design moderno e praticidade no dia a dia.',
    category: 'Casa',
    imageSrc: '/presentes/cs_08.jpg',
    suggestedAmount: 75,
    minimumContribution: MINIMUM_CONTRIBUTION,
    referenceTotal: 749.9,
    quotaCount: 10,
    order: 30,
    priceSourceUrl: PRICE_SOURCE_URL,
    imageSourceUrl: 'https://www.rawpixel.com/image/6042998/photo-image-public-domain-house-kitchen',
    priceCheckedAt: PRICE_CHECKED_AT,
  },
  {
    id: 'cs_09',
    title: 'Jogo de Taças de Cristal',
    description: 'Para os brindes de comemoração.',
    category: 'Casa',
    imageSrc: '/presentes/cs_09.jpg',
    suggestedAmount: 80,
    minimumContribution: MINIMUM_CONTRIBUTION,
    referenceTotal: 329,
    quotaCount: 4,
    order: 31,
    priceSourceUrl: PRICE_SOURCE_URL,
    imageSourceUrl: 'https://www.flickr.com/photos/11121785@N00/121601423',
    priceCheckedAt: PRICE_CHECKED_AT,
  },
  {
    id: 'cs_10',
    title: 'Liquidificador Potente',
    description: 'Com copo de vidro resistente para vitaminas e sucos.',
    category: 'Casa',
    imageSrc: '/presentes/cs_10.jpg',
    suggestedAmount: 70,
    minimumContribution: MINIMUM_CONTRIBUTION,
    referenceTotal: 289,
    quotaCount: 4,
    order: 32,
    priceSourceUrl: PRICE_SOURCE_URL,
    imageSourceUrl: 'https://www.flickr.com/photos/83136374@N05/49907001146',
    priceCheckedAt: PRICE_CHECKED_AT,
  },
  {
    id: 'cs_11',
    title: 'Aparelho de Jantar 30 Peças',
    description: 'Porcelana resistente para todas as refeições.',
    category: 'Casa',
    imageSrc: '/presentes/cs_11.jpg',
    suggestedAmount: 90,
    minimumContribution: MINIMUM_CONTRIBUTION,
    referenceTotal: 539,
    quotaCount: 6,
    order: 33,
    priceSourceUrl: PRICE_SOURCE_URL,
    imageSourceUrl: 'https://www.flickr.com/photos/49889671@N03/8262326054',
    priceCheckedAt: PRICE_CHECKED_AT,
  },
  {
    id: 'cs_12',
    title: 'Kit de Tábuas e Facas do Chef',
    description: 'Equipamento essencial para cozinhar melhor.',
    category: 'Casa',
    imageSrc: '/presentes/cs_12.jpg',
    suggestedAmount: 65,
    minimumContribution: MINIMUM_CONTRIBUTION,
    referenceTotal: 189.9,
    quotaCount: 3,
    order: 34,
    priceSourceUrl: PRICE_SOURCE_URL,
    imageSourceUrl: 'https://www.flickr.com/photos/87481332@N00/149291464',
    priceCheckedAt: PRICE_CHECKED_AT,
  },
  {
    id: 'cs_13',
    title: 'Ferro de Passar a Vapor',
    description: 'Para roupas impecaveis antes do trabalho.',
    category: 'Casa',
    imageSrc: '/presentes/cs_13.jpg',
    suggestedAmount: 60,
    minimumContribution: MINIMUM_CONTRIBUTION,
    referenceTotal: 249,
    quotaCount: 4,
    order: 35,
    priceSourceUrl: PRICE_SOURCE_URL,
    imageSourceUrl: 'https://www.rawpixel.com/image/8809317/photo-image-public-domain-product',
    priceCheckedAt: PRICE_CHECKED_AT,
  },
  {
    id: 'cs_14',
    title: 'Câmera de Segurança Wi-Fi',
    description: 'Monitoramento interno para segurança da nova casa.',
    category: 'Casa',
    imageSrc: '/presentes/cs_14.jpg',
    suggestedAmount: 90,
    minimumContribution: MINIMUM_CONTRIBUTION,
    referenceTotal: 359,
    quotaCount: 4,
    order: 36,
    priceSourceUrl: PRICE_SOURCE_URL,
    imageSourceUrl: 'https://images.unsplash.com/photo-1557597774-9d273605dfa9',
    priceCheckedAt: PRICE_CHECKED_AT,
  },
  {
    id: 'cs_15',
    title: 'Geladeira Frost Free Inox',
    description: 'O eletrodoméstico mais importante da cozinha.',
    category: 'Casa',
    imageSrc: '/presentes/cs_15.jpg',
    suggestedAmount: 110,
    minimumContribution: MINIMUM_CONTRIBUTION,
    referenceTotal: 4299,
    quotaCount: 40,
    order: 37,
    priceSourceUrl: PRICE_SOURCE_URL,
    imageSourceUrl: 'https://www.flickr.com/photos/66992990@N00/6040059574',
    priceCheckedAt: PRICE_CHECKED_AT,
  },
];
