from __future__ import annotations

import json
from pathlib import Path

import gdown
import requests
from PIL import Image, ImageOps


FOLDER_ID = "12-Z1XZthZkDNFvfo-fuyHGBiF_JFhYDA"
MAX_EDGE = 1800
WEBP_QUALITY = 82
HERO_SELECTION = [126, 136, 381]
HOME_PREVIEW_SELECTION = [126, 136, 129, 325, 321, 366, 373, 381, 412, 415, 454, 460]

SELECTION = [
    14,
    15,
    17,
    18,
    20,
    22,
    38,
    48,
    49,
    60,
    64,
    70,
    71,
    72,
    107,
    108,
    112,
    116,
    118,
    121,
    123,
    125,
    126,
    129,
    131,
    136,
    148,
    150,
    154,
    157,
    178,
    203,
    219,
    229,
    232,
    236,
    261,
    270,
    271,
    300,
    302,
    303,
    306,
    308,
    318,
    321,
    325,
    326,
    329,
    351,
    361,
    366,
    373,
    374,
    379,
    381,
    401,
    412,
    415,
    433,
    436,
    454,
    460,
]


ROOT = Path(__file__).resolve().parents[1]
SOURCE_DIR = ROOT / "output" / "galeria-noivos" / "source-jpg"
PUBLIC_DIR = ROOT / "public" / "galeria-noivos"
GALLERY_TS = ROOT / "lib" / "gallery.ts"


def drive_name(number: int) -> str:
    return f"EnIM-{number:02d}.jpg"


def asset_stem(number: int) -> str:
    return f"enim-{number:03d}"


def orientation_for(width: int, height: int) -> str:
    if width == height:
        return "square"
    return "landscape" if width > height else "portrait"


def resize_for_web(image: Image.Image) -> Image.Image:
    width, height = image.size
    longest = max(width, height)
    if longest <= MAX_EDGE:
        return image

    scale = MAX_EDGE / longest
    resized_size = (round(width * scale), round(height * scale))
    return image.resize(resized_size, Image.Resampling.LANCZOS)


def is_valid_image(path: Path) -> bool:
    if not path.exists() or path.stat().st_size == 0:
        return False

    try:
        with Image.open(path) as image:
            image.verify()
        return True
    except Exception:
        return False


def download_drive_file(file_id: str, output_path: Path) -> None:
    url = "https://drive.usercontent.google.com/download"
    params = {"id": file_id, "export": "download", "confirm": "t"}
    temp_path = output_path.with_suffix(output_path.suffix + ".part")

    with requests.get(url, params=params, stream=True, timeout=(15, 180)) as response:
        response.raise_for_status()
        content_type = response.headers.get("Content-Type", "")
        if "text/html" in content_type:
            raise RuntimeError(f"Google Drive returned HTML instead of an image for {output_path.name}")

        with temp_path.open("wb") as output:
            for chunk in response.iter_content(chunk_size=1024 * 1024):
                if chunk:
                    output.write(chunk)

    temp_path.replace(output_path)


def build_gallery_ts(items: list[dict[str, object]]) -> str:
    lines = [
        "export type GalleryImage = {",
        "  id: string;",
        "  src: string;",
        "  alt: string;",
        "  width: number;",
        "  height: number;",
        '  orientation: "portrait" | "landscape" | "square";',
        "  featured?: boolean;",
        "};",
        "",
        "// Generated by scripts/build-couple-gallery-assets.py from the approved pre-wedding selection.",
        "export const coupleGalleryImages: GalleryImage[] = [",
    ]

    for item in items:
        lines.extend(
            [
                "  {",
                f'    id: "{item["id"]}",',
                f'    src: "{item["src"]}",',
                f'    alt: "{item["alt"]}",',
                f'    width: {item["width"]},',
                f'    height: {item["height"]},',
                f'    orientation: "{item["orientation"]}",',
                "  },",
            ]
        )

    lines.extend(
        [
            "];",
            "",
            "export const coupleGalleryHeroImages = [",
            *[
                f'  "/galeria-noivos/{asset_stem(number)}.webp",'
                for number in HERO_SELECTION
            ],
            "];",
            "",
            "export const coupleHomePreviewImages = [",
            *[
                f'  "/galeria-noivos/{asset_stem(number)}.webp",'
                for number in HOME_PREVIEW_SELECTION
            ],
            "];",
            "",
        ]
    )
    return "\n".join(lines)


def main() -> None:
    SOURCE_DIR.mkdir(parents=True, exist_ok=True)
    PUBLIC_DIR.mkdir(parents=True, exist_ok=True)

    print("Listing Google Drive folder...", flush=True)
    drive_files = gdown.download_folder(
        id=FOLDER_ID,
        output=str(SOURCE_DIR),
        quiet=True,
        skip_download=True,
    )
    drive_ids = {file.path: file.id for file in drive_files}

    missing = [drive_name(number) for number in SELECTION if drive_name(number) not in drive_ids]
    if missing:
        raise SystemExit("Missing selected files in Drive: " + ", ".join(missing))

    items: list[dict[str, object]] = []

    for index, number in enumerate(SELECTION, start=1):
        source_name = drive_name(number)
        source_path = SOURCE_DIR / source_name
        output_path = PUBLIC_DIR / f"{asset_stem(number)}.webp"

        if not is_valid_image(source_path):
            print(f"Downloading {source_name} ({index}/{len(SELECTION)})...", flush=True)
            download_drive_file(drive_ids[source_name], source_path)
        else:
            print(f"Using cached {source_name} ({index}/{len(SELECTION)})...", flush=True)

        with Image.open(source_path) as original:
            image = ImageOps.exif_transpose(original).convert("RGB")
            image = resize_for_web(image)
            image.save(output_path, "WEBP", quality=WEBP_QUALITY, method=6)
            width, height = image.size

        items.append(
            {
                "id": asset_stem(number),
                "src": f"/galeria-noivos/{asset_stem(number)}.webp",
                "alt": f"Isadora e Matheus no ensaio pre-wedding - foto {number}",
                "width": width,
                "height": height,
                "orientation": orientation_for(width, height),
            }
        )

    GALLERY_TS.write_text(build_gallery_ts(items), encoding="utf-8")

    manifest_path = ROOT / "output" / "galeria-noivos" / "manifest.json"
    manifest_path.write_text(
        json.dumps(
            {
                "folderId": FOLDER_ID,
                "maxEdge": MAX_EDGE,
                "webpQuality": WEBP_QUALITY,
                "count": len(items),
                "items": items,
            },
            ensure_ascii=False,
            indent=2,
        )
        + "\n",
        encoding="utf-8",
    )

    total_size = sum(path.stat().st_size for path in PUBLIC_DIR.glob("*.webp"))
    print(f"Generated {len(items)} WebP files in {PUBLIC_DIR}", flush=True)
    print(f"Total public gallery size: {total_size / 1024 / 1024:.2f} MB", flush=True)


if __name__ == "__main__":
    main()
